test_p1 (__main__.Test.test_p1) ... ok
test_p2 (__main__.Test.test_p2) ... ok
test_p3 (__main__.Test.test_p3) ... ok
test_p4 (__main__.Test.test_p4) ... FAIL
test_p5 (__main__.Test.test_p5) ... ok
test_p6 (__main__.Test.test_p6) ... ok

======================================================================
FAIL: test_p4 (__main__.Test.test_p4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\wikto\OneDrive\Pulpit\Nowy folder\tester.py", line 27, in test_p4
    self.assertEqual(p4.f(99887766),"9+9+8++8++7+7+6++6")
AssertionError: '9+9+8++8++7+7+66' != '9+9+8++8++7+7+6++6'
- 9+9+8++8++7+7+66
+ 9+9+8++8++7+7+6++6
?                ++


----------------------------------------------------------------------
Ran 6 tests in 0.006s

FAILED (failures=1)
